import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "ka" | "en" | "ru" | "tr";

export interface I18nString {
  ka: string;
  en: string;
  ru: string;
  tr: string;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.en) => string;
  getText: (obj: I18nString | string | unknown) => string;
}

const translations = {
  ka: {
    home: "მთავარი",
    aboutUs: "ჩვენს შესახებ",
    services: "სერვისები",
    team: "გუნდი",
    partners: "პარტნიორები",
    insights: "სიახლეები",
    contact: "კონტაქტი",
    contacts: "კონტაქტები",
    getConsultation: "მიიღეთ კონსულტაცია",
    heroTitle: "ACG",
    heroTitleHighlight: "ქუთაისის ფილიალი",
    heroDescription: "ადგილი, სადაც ხარისხი სერვისს ხვდება და წარმატებისკენ სწრაფვა სავალდებულოა. ჩვენ ვართ ბიზნესმენები, რომლებიც ცოდნას და გამოცდილებას იყენებენ ჩვენი კლიენტების პრობლემების გადასაჭრელად.",
    exploreServices: "სერვისების ნახვა",
    yearsExperience: "წლიანი გამოცდილება",
    corporateClients: "კორპორატიული კლიენტი",
    successfulAudits: "წარმატებული აუდიტი",
    consultants: "კონსულტანტი",
    ourExpertise: "ჩვენი ექსპერტიზა",
    comprehensiveSolutions: "კომპლექსური ფინანსური გადაწყვეტილებები",
    viewAllServices: "ყველა სერვისის ნახვა",
    learnMore: "გაიგეთ მეტი",
    whyChooseUs: "რატომ ჩვენ",
    partnerYouCanTrust: "პარტნიორი, რომელსაც შეგიძლიათ ენდოთ",
    trustDescription: "ჩვენ გვჯერა გრძელვადიანი პარტნიორობის შექმნის გამჭვირვალობის, ექსპერტიზისა და გაზომვადი შედეგების საფუძველზე.",
    strategicInsight: "სტრატეგიული ხედვა",
    strategicInsightDesc: "მონაცემებზე დაფუძნებული გადაწყვეტილებები მდგრადი ზრდისთვის.",
    globalCompliance: "გლობალური შესაბამისობა",
    globalComplianceDesc: "საერთაშორისო რეგულაციების ექსპერტული ნავიგაცია.",
    riskMitigation: "რისკების შერბილება",
    riskMitigationDesc: "ფინანსური საფრთხეების პროაქტიული იდენტიფიკაცია.",
    readyToElevate: "მზად ხართ თქვენი ფინანსური სტრატეგიის გასაუმჯობესებლად?",
    scheduleConsultation: "დანიშნეთ კონსულტაცია ჩვენს უფროს პარტნიორებთან და აღმოაჩინეთ, როგორ შეგვიძლია დაგეხმაროთ.",
    getStartedToday: "დაიწყეთ დღეს",
    ourPeople: "ჩვენი ხალხი",
    meetThePartners: "გაიცანით პარტნიორები",
    teamDescription: "ჩვენი გუნდი აერთიანებს ათწლეულების გამოცდილებას წამყვანი ფირმებიდან.",
    insightsAndNews: "სიახლეები და ახალი ამბები",
    insightsDescription: "ექსპერტული პერსპექტივები მარეგულირებელ ცვლილებებზე და ფინანსურ სტრატეგიებზე.",
    readArticle: "წაიკითხეთ სტატია",
    ourServices: "ჩვენი სერვისები",
    servicesDescription: "კომპლექსური აუდიტი, საგადასახადო და საკონსულტაციო გადაწყვეტილებები.",
    viewDetails: "დეტალების ნახვა",
    contactUs: "დაგვიკავშირდით",
    contactDescription: "მზად ხართ საუბრის დასაწყებად? ჩვენ აქ ვართ დასახმარებლად.",
    sendMessage: "გაგზავნეთ შეტყობინება",
    formDescription: "შეავსეთ ფორმა და ჩვენი გუნდი მალე დაგიკავშირდებათ.",
    fullName: "სრული სახელი",
    emailAddress: "ელ. ფოსტა",
    phoneOptional: "ტელეფონი (არასავალდებულო)",
    companyOptional: "კომპანია (არასავალდებულო)",
    howCanWeHelp: "როგორ შეგვიძლია დაგეხმაროთ?",
    tellUsRequirements: "გვითხარით თქვენი მოთხოვნილებების შესახებ...",
    sendingMessage: "იგზავნება...",
    messageSent: "შეტყობინება გაიგზავნა",
    thankYouMessage: "გმადლობთ დაკავშირებისთვის. 24 საათში გიპასუხებთ.",
    error: "შეცდომა",
    contactInformation: "საკონტაქტო ინფორმაცია",
    headquarters: "მთავარი ოფისი",
    officeAddress: "წერეთლის 12, ქუთაისი, საქართველო",
    emailUs: "მოგვწერეთ",
    callUs: "დაგვირეკეთ",
    officeHours: "სამუშაო საათები",
    company: "კომპანია",
    servicesFooter: "სერვისები",
    contactFooter: "კონტაქტი",
    allRightsReserved: "ყველა უფლება დაცულია",
    privacyPolicy: "კონფიდენციალურობის პოლიტიკა",
    termsOfService: "მომსახურების პირობები",
    serviceNotFound: "სერვისი ვერ მოიძებნა",
    backToServices: "სერვისებზე დაბრუნება",
    brandDescription: "გლობალური ბიზნესის მომავლის ფორმირება - ვაერთიანებთ დამოუკიდებელ პროფესიონალებს მსოფლიო მასშტაბით.",
    auditAssurance: "აუდიტი და გარანტია",
    auditDescription: "აუდიტი ბევრად მეტია, ვიდრე ფორმალობა. ეს რეალური აუცილებლობაა ბიზნესის დასაცავად და წასახალისებლად.",
    financialServices: "ფინანსური მომსახურება",
    financialDescription: "ACG უზრუნველყოფს სრულ მომსახურებას ნებისმიერი ზომის კლიენტებისთვის — სტარტაპებიდან მსხვილ კერძო და საჯარო კომპანიებამდე. ჩვენი ფინანსური მომსახურების გუნდი დაგეხმარებათ ფინანსების ეფექტურად მართვასა და მდგრადი ზრდის დაგეგმვაში.",
    consultingServices: "საკონსულტაციო მომსახურება",
    consultingDescription: "ჩვენი პროფესიონალები სხვადასხვა მულტიდისციპლინური გამოცდილებით გთავაზობენ ეფექტურ გადაწყვეტილებებს. ჩვენ ვაწვდით სტრატეგიულ ხელმძღვანელობას ბიზნეს-სტრუქტურის, ზრდის სტრატეგიებისა და ოპერაციული ეფექტურობის საკითხებში.",
    businessStructure: "ბიზნეს სტრუქტურა",
    businessStructureDesc: "კომპანიის ორგანიზაციული სტრუქტურის ოპტიმიზაცია და რეორგანიზაცია მაქსიმალური ეფექტურობისთვის.",
    growthStrategies: "ზრდის სტრატეგიები",
    growthStrategiesDesc: "ბიზნესის გაფართოებისა და განვითარების სტრატეგიული გეგმების შემუშავება.",
    operationalEfficiency: "ოპერაციული ეფექტურობა",
    operationalEfficiencyDesc: "ბიზნეს პროცესების ოპტიმიზაცია ხარჯების შემცირებისა და პროდუქტიულობის გაზრდისთვის.",
    multidisciplinaryTeam: "მულტიდისციპლინური გუნდი",
    multidisciplinaryTeamDesc: "სხვადასხვა დარგის ექსპერტების გაერთიანებული გამოცდილება თქვენი ბიზნესის სასარგებლოდ.",
    taxConsultancy: "საგადასახადო კონსულტაცია",
    financialAdvisory: "ფინანსური კონსულტაცია",
    riskManagement: "რისკების მართვა",
    corporateFinance: "კორპორატიული ფინანსები",
    recently: "ახლახანს",
    mondayFriday: "ორშაბათი - პარასკევი: 9:00 - 18:00",
    saturdaySunday: "შაბათი - კვირა: დაკეტილია",
    integrityQuote: "მთლიანობა ჩვენი პრაქტიკის საფუძველია.",
    modernBuilding: "თანამედროვე კორპორატიული შენობა",
    ourTeamAlt: "ჩვენი გუნდი",
    mapPlaceholder: "რუკის ინტეგრაცია",
    openInMaps: "Google Maps-ში გახსნა",
    viewPortfolio: "პორტფოლიოს ნახვა",
    generalEmail: "ზოგადი",
    supportEmail: "მხარდაჭერა",
    mainPhone: "მთავარი",
    faxPhone: "ფაქსი",
    clientSuccess: "კლიენტის წარმატება",
    aboutTitle: "ACG-ს შესახებ",
    aboutSubtitle: "ჩვენ ვართ წამყვანი აუდიტორული და საკონსულტაციო კომპანია, რომელიც ყველა კლიენტისათვის ინდივიდუალური გადაწყვეტილების გეოგრაფიონს.",
    aboutWhoWeAre: "ვინ ვართ ჩვენ",
    aboutWhoWeAreDesc: "ჩვენ ვართ ბიზნესმენები, რომლებიც ცოდნას და გამოცდილებას იყენებენ ჩვენი კლიენტების პრობლემების გადასაჭრელად. ჩვენთვის კარგი საკმარისი არ არის. ჩვენ მიზნად ვისახავთ ვიყოთ საუკეთესო ყველაფერში, რასაც ვაკეთებთ. ACG-ს ფილოსოფიის მთავარი მიმართულება არის მაღალი ხარისხის და სრულად ერთგული მომსახურება დიდი და მცირე კლიენტებისთვის. ეს მაღალი სტანდარტები აუცილებელია ქვეყნის განვითარებისა და ინვესტიციების მოზიდვისთვის.",
    aboutIntegraDesc: "როგორც Integra International-ის წევრი, დამოუკიდებელი ბუღალტრული და ბიზნეს საკონსულტაციო ფირმების გლობალური ასოციაცია, ჩვენ ვთავაზობთ ჩვენს კლიენტებს 4000+ პროფესიონალის ცოდნასა და გამოცდილებას 75+ ქვეყანაში. ეს გლობალური წვდომა უზრუნველყოფს, რომ სადაც არ უნდა წაგიყვანოთ ბიზნესმა, ჩვენ გვაქვს კავშირები თქვენი მხარდაჭერისთვის.",
    aboutMission: "ჩვენი მისია",
    aboutMissionDesc: "ჩვენი მიზანია შევქმნათ რაღაც ჯადოსნური თქვენსა და ჩვენს შორის, გავაერთიანოთ ენერგიები და შესაძლებლობები, რომ დაგეხმაროთ თქვენი ბიზნესის მართვაში უფრო ორგანიზებულად და მარტივად, რომ თქვენც თავად მოახდინოთ შთაბეჭდილება თქვენს კლიენტებზე.",
    aboutJoinSuccess: "ჩვენი გამოცდილება დაგეხმარებათ წარმატების მიღწევაში!",
    aboutExcellence: "სრულყოფილება",
    aboutExcellenceDesc: "ყველაზე მაღალსტანდარტულიანი მომსახურება.",
    aboutPartnership: "პარტნიორობა",
    aboutPartnershipDesc: "კლიენტზე ორიენტირებული მიდგომა.",
    aboutStatClients: "გავრცელი კორპულარტივბინ",
    aboutStatProjects: "წარმატებული კლიენტები",
    aboutStatOffices: "ოფისი მსოფლიუშ",
    aboutStatConsultations: "წარმატებული პროექტები",
    aboutMeetingAlt: "საქმიანი შეხვედრა",
    backToTeam: "გუნდში დაბრუნება",
    notFound: "გვერდი ვერ მოიძებნა",
    loanPurposeVerification: "სესხის მიზნობრიობის დადასტურება",
    accountingLegislation: "ბუღალტრული აღრიცხვის და კანონმდებლობის შესწავლა",
    legalServices: "სამართლებრივი მომსახურება",
    propertyValuation: "ქონების შეფასება",
    consulting: "კონსალტინგი",
    taxDisputesConsulting: "საგადასახადო დავა და კონსულტაცია",
    blockchainWeb3: "ბლოკჩეინი და Web3 გადაწყვეტილებები",
    blockchainSubtitle: "თანამედროვე ბლოკჩეინ განვითარება, სმარტ კონტრაქტების აუდიტი და დეცენტრალიზებული აპლიკაციების გადაწყვეტილებები თანამედროვე საწარმოებისთვის.",
    blockchainIntro: "სწრაფად განვითარებად ციფრულ ლანდშაფტში ბლოკჩეინ ტექნოლოგია წარმოადგენს პარადიგმულ ცვლილებას იმაში, თუ როგორ მუშაობს, ახორციელებს ტრანზაქციებს და აშენებს ნდობას ბიზნესი. ACG-ის ბლოკჩეინი და Web3 გადაწყვეტილებების განყოფილება მოაქვს საწარმოს დონის ბლოკჩეინ ექსპერტიზა, რათა დაეხმაროს თქვენს ორგანიზაციას დეცენტრალიზებული ტექნოლოგიების ტრანსფორმაციული ძალის გამოყენებაში.",
    smartContractTitle: "სმარტ კონტრაქტების შემუშავება და აუდიტი",
    smartContractDesc: "ჩვენი გუნდი ავითარებს უსაფრთხო, ეფექტურ სმარტ კონტრაქტებს EVM-ზე დაფუძნებულ ბლოკჩეინ პლატფორმებზე, მათ შორის Ethereum-სა და Polygon-ზე. ყოველი კონტრაქტი გადის მკაცრ უსაფრთხოების აუდიტს, რათა გამოავლინოს დაუცველობები განლაგებამდე, იცავს თქვენს აქტივებსა და რეპუტაციას.",
    tokenizationTitle: "ტოკენიზაცია და ციფრული აქტივები",
    tokenizationDesc: "უტილიტარული ტოკენებიდან უსაფრთხოების ტოკენებამდე და NFT-ებამდე, ჩვენ გაგიძღვებით მთელ ტოკენიზაციის პროცესში. ჩვენი მომსახურება მოიცავს ტოკენომიკის დიზაინს, სმარტ კონტრაქტების იმპლემენტაციას, მარეგულირებელ შესაბამისობის კონსულტაციას და ინტეგრაციას არსებულ ბიზნეს-სისტემებთან.",
    defiTitle: "DeFi გადაწყვეტილებები",
    defiDesc: "ჩვენ ვაპროექტებთ და ვავითარებთ დეცენტრალიზებული ფინანსების პროტოკოლებს, მათ შორის სესხის პლატფორმებს, დეცენტრალიზებულ ბირჟებს, შემოსავლიანი ფერმერობის მექანიზმებსა და ლიკვიდობის აუზებს. ჩვენი გადაწყვეტილებები პრიორიტეტს ანიჭებს უსაფრთხოებას, მასშტაბირებადობას და მომხმარებლის გამოცდილებას.",
    enterpriseBlockchainTitle: "საწარმოს ბლოკჩეინ ინტეგრაცია",
    enterpriseBlockchainDesc: "დააკავშირეთ ტრადიციული ბიზნეს-ოპერაციები ბლოკჩეინ ტექნოლოგიასთან. ჩვენ ვანერგავთ კერძო და კონსორციუმის ბლოკჩეინ ქსელებს მიწოდების ჯაჭვის თვალყურის დევნებისთვის, დოკუმენტების ვერიფიკაციისთვის, ტრანსსასაზღვრო გადახდებისა და გამჭვირვალე აუდიტის პროცესებისთვის.",
    web3AppTitle: "Web3 აპლიკაციების შემუშავება",
    web3AppDesc: "ააშენეთ მომავალი დეცენტრალიზებული აპლიკაციებით (dApps), რომლებიც იყენებენ ბლოკჩეინს უნდობლო ოპერაციებისთვის. კონცეფციიდან განლაგებამდე, ჩვენი სრული სტეკის Web3 განვითარების მომსახურება მოიცავს ფრონტენდ ინტერფეისებს, სმარტ კონტრაქტის ბექენდებსა და საფულეების ინტეგრაციებს.",
  },
  en: {
    home: "Home",
    aboutUs: "About Us",
    services: "Services",
    team: "Team",
    partners: "Partners",
    insights: "Insights",
    contact: "Contact",
    contacts: "Contacts",
    getConsultation: "Get a Consultation",
    heroTitle: "ACG",
    heroTitleHighlight: "Kutaisi Branch",
    heroDescription: "A place where quality meets service and striving for success is mandatory. We are business professionals who use knowledge and experience to solve our clients' problems.",
    exploreServices: "Explore Services",
    yearsExperience: "Years Experience",
    corporateClients: "Corporate Clients",
    successfulAudits: "Successful Audits",
    consultants: "Consultants",
    ourExpertise: "Our Expertise",
    comprehensiveSolutions: "Comprehensive Financial Solutions",
    viewAllServices: "View All Services",
    learnMore: "Learn more",
    whyChooseUs: "Why Choose Us",
    partnerYouCanTrust: "A Partner You Can Trust",
    trustDescription: "We believe in building long-term partnerships based on transparency, expertise, and measurable results.",
    strategicInsight: "Strategic Insight",
    strategicInsightDesc: "Data-driven decisions for sustainable growth.",
    globalCompliance: "Global Compliance",
    globalComplianceDesc: "Expert navigation of international regulations.",
    riskMitigation: "Risk Mitigation",
    riskMitigationDesc: "Proactive identification of financial threats.",
    readyToElevate: "Ready to elevate your financial strategy?",
    scheduleConsultation: "Schedule a consultation with our senior partners today and discover how we can help optimize your business performance.",
    getStartedToday: "Get Started Today",
    ourPeople: "Our People",
    meetThePartners: "Meet the Partners",
    teamDescription: "Our team brings together decades of experience from top-tier firms, united by a passion for excellence and client success.",
    insightsAndNews: "Insights & News",
    insightsDescription: "Expert perspectives on regulatory changes, market trends, and financial strategies.",
    readArticle: "Read Article",
    ourServices: "Our Services",
    servicesDescription: "Comprehensive audit, tax, and advisory solutions tailored to your unique business challenges.",
    viewDetails: "View Details",
    contactUs: "Contact Us",
    contactDescription: "Ready to start a conversation? We're here to help you navigate your financial future.",
    sendMessage: "Send Message",
    formDescription: "Fill out the form below and our team will get back to you shortly.",
    fullName: "Full Name",
    emailAddress: "Email Address",
    phoneOptional: "Phone (Optional)",
    companyOptional: "Company (Optional)",
    howCanWeHelp: "How can we help?",
    tellUsRequirements: "Tell us about your requirements...",
    sendingMessage: "Sending Message...",
    messageSent: "Message Sent",
    thankYouMessage: "Thank you for contacting us. We will respond within 24 hours.",
    error: "Error",
    contactInformation: "Contact Information",
    headquarters: "Headquarters",
    officeAddress: "12 Tsereteli St, Kutaisi, Georgia",
    emailUs: "Email Us",
    callUs: "Call Us",
    officeHours: "Office Hours",
    company: "Company",
    servicesFooter: "Services",
    contactFooter: "Contact",
    allRightsReserved: "All rights reserved",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    serviceNotFound: "Service Not Found",
    backToServices: "Back to Services",
    brandDescription: "Shaping the future of global business - bringing together independent professionals on a worldwide scale.",
    auditAssurance: "Audit & Assurance",
    auditDescription: "Audit is much more than a formality. It is a real necessity to protect and encourage business.",
    financialServices: "Financial Services",
    financialDescription: "ACG provides comprehensive services for clients of all sizes — from startups to large private and public companies. Our financial services team will help you manage finances effectively and plan sustainable growth.",
    consultingServices: "Consulting Services",
    consultingDescription: "Our professionals with diverse multidisciplinary experience offer effective solutions. We provide strategic guidance on business structure, growth strategies, and operational efficiency.",
    businessStructure: "Business Structure",
    businessStructureDesc: "Optimization and reorganization of company organizational structure for maximum efficiency.",
    growthStrategies: "Growth Strategies",
    growthStrategiesDesc: "Development of strategic plans for business expansion and development.",
    operationalEfficiency: "Operational Efficiency",
    operationalEfficiencyDesc: "Business process optimization to reduce costs and increase productivity.",
    multidisciplinaryTeam: "Multidisciplinary Team",
    multidisciplinaryTeamDesc: "Combined expertise of specialists from various fields for the benefit of your business.",
    taxConsultancy: "Tax Consultancy",
    financialAdvisory: "Financial Advisory",
    riskManagement: "Risk Management",
    corporateFinance: "Corporate Finance",
    recently: "Recently",
    mondayFriday: "Monday - Friday: 9:00 AM - 6:00 PM EST",
    saturdaySunday: "Saturday - Sunday: Closed",
    integrityQuote: "Integrity is the foundation of our practice.",
    modernBuilding: "Modern Corporate Building",
    ourTeamAlt: "Our Team",
    mapPlaceholder: "Map Integration",
    openInMaps: "Open in Google Maps",
    viewPortfolio: "View Portfolio",
    generalEmail: "General",
    supportEmail: "Support",
    mainPhone: "Main",
    faxPhone: "Fax",
    clientSuccess: "Client Success",
    aboutTitle: "About ACG",
    aboutSubtitle: "We are a leading audit and consulting company that provides individual solutions for every client.",
    aboutWhoWeAre: "Who We Are",
    aboutWhoWeAreDesc: "We are motivated professionals who use knowledge and experience to solve our clients' problems. Our approach is not standard. Our clients rely on the best auditors to work effectively. ACG's core philosophy is high quality service delivery and complete client protection with comprehensive support. This high standardization is ensured by our career and industry requirements.",
    aboutIntegraDesc: "As a member of Integra International, a philanthropic and leading international financial partnership, we offer our clients access to 4000+ professionals across 75+ countries. This international support guarantees that we always provide our clients with qualified multi-format services.",
    aboutMission: "Our Mission",
    aboutMissionDesc: "Our support for our clients through strategic management and monitoring ensures that client services are delivered effectively and completely, so that every customer feels cared for and in control.",
    aboutJoinSuccess: "Our experience will help you achieve success!",
    aboutExcellence: "Excellence",
    aboutExcellenceDesc: "Highest standard service delivery.",
    aboutPartnership: "Partnership",
    aboutPartnershipDesc: "Client-oriented approach.",
    aboutStatClients: "Corporate Clients",
    aboutStatProjects: "Successful Clients",
    aboutStatOffices: "Offices Worldwide",
    aboutStatConsultations: "Successful Projects",
    aboutMeetingAlt: "Business Meeting",
    backToTeam: "Back to Team",
    notFound: "Page Not Found",
    loanPurposeVerification: "Loan Purpose Verification",
    accountingLegislation: "Accounting & Legislation Study",
    legalServices: "Legal Services",
    propertyValuation: "Property Valuation",
    consulting: "Consulting",
    taxDisputesConsulting: "Tax Disputes & Consulting",
    blockchainWeb3: "Blockchain & Web3 Solutions",
    blockchainSubtitle: "Modern blockchain development, smart contract auditing, and decentralized application solutions for modern enterprises.",
    blockchainIntro: "In a rapidly evolving digital landscape, blockchain technology represents a paradigm shift in how business operates, conducts transactions and builds trust. ACG's Blockchain and Web3 Solutions division brings enterprise-grade blockchain expertise to help your organization harness the transformative power of decentralized technologies.",
    smartContractTitle: "Smart Contract Development and Audit",
    smartContractDesc: "Our team develops secure, efficient smart contracts on EVM-based blockchain platforms, including Ethereum and Polygon. Every contract undergoes rigorous security audits to identify vulnerabilities before deployment, protecting your assets and reputation.",
    tokenizationTitle: "Tokenization and Digital Assets",
    tokenizationDesc: "From utility tokens to security tokens and NFTs, we guide you through the entire tokenization process. Our services include tokenomics design, smart contract implementation, regulatory compliance consulting and integration with existing business systems.",
    defiTitle: "DeFi Solutions",
    defiDesc: "We design and develop decentralized finance protocols, including lending platforms, decentralized exchanges, yield farming mechanisms and liquidity pools. Our solutions prioritize security, scalability and user experience.",
    enterpriseBlockchainTitle: "Enterprise Blockchain Integration",
    enterpriseBlockchainDesc: "Connect traditional business operations with blockchain technology. We implement private and consortium blockchain networks for supply chain tracking, document verification, cross-border payments and transparent audit processes.",
    web3AppTitle: "Web3 Application Development",
    web3AppDesc: "Build the future with decentralized applications (dApps) that leverage blockchain for trustless operations. From concept to deployment, our full-stack Web3 development services cover frontend interfaces, smart contract backends and wallet integrations.",
  },
  ru: {
    home: "Главная",
    aboutUs: "О нас",
    services: "Услуги",
    team: "Команда",
    partners: "Партнеры",
    insights: "Инсайты",
    contact: "Контакт",
    contacts: "Контакты",
    getConsultation: "Получить консультацию",
    heroTitle: "ACG",
    heroTitleHighlight: "Кутаисский филиал",
    heroDescription: "Место, где качество встречается с сервисом, а стремление к успеху обязательно. Мы - бизнес-профессионалы, использующие знания и опыт для решения проблем наших клиентов.",
    exploreServices: "Изучить услуги",
    yearsExperience: "Лет опыта",
    corporateClients: "Корпоративных клиентов",
    successfulAudits: "Успешных аудитов",
    consultants: "Консультантов",
    ourExpertise: "Наша экспертиза",
    comprehensiveSolutions: "Комплексные финансовые решения",
    viewAllServices: "Все услуги",
    learnMore: "Узнать больше",
    whyChooseUs: "Почему мы",
    partnerYouCanTrust: "Партнер, которому можно доверять",
    trustDescription: "Мы верим в построение долгосрочных партнерств, основанных на прозрачности, экспертизе и измеримых результатах.",
    strategicInsight: "Стратегическое видение",
    strategicInsightDesc: "Решения на основе данных для устойчивого роста.",
    globalCompliance: "Глобальное соответствие",
    globalComplianceDesc: "Экспертная навигация международных регуляций.",
    riskMitigation: "Снижение рисков",
    riskMitigationDesc: "Проактивное выявление финансовых угроз.",
    readyToElevate: "Готовы улучшить свою финансовую стратегию?",
    scheduleConsultation: "Запланируйте консультацию с нашими старшими партнерами и узнайте, как мы можем помочь.",
    getStartedToday: "Начните сегодня",
    ourPeople: "Наши люди",
    meetThePartners: "Познакомьтесь с партнерами",
    teamDescription: "Наша команда объединяет десятилетия опыта из ведущих фирм.",
    insightsAndNews: "Инсайты и новости",
    insightsDescription: "Экспертные перспективы по регуляторным изменениям и финансовым стратегиям.",
    readArticle: "Читать статью",
    ourServices: "Наши услуги",
    servicesDescription: "Комплексные решения по аудиту, налогам и консультированию.",
    viewDetails: "Подробнее",
    contactUs: "Свяжитесь с нами",
    contactDescription: "Готовы начать разговор? Мы здесь, чтобы помочь вам.",
    sendMessage: "Отправить сообщение",
    formDescription: "Заполните форму, и наша команда свяжется с вами.",
    fullName: "Полное имя",
    emailAddress: "Электронная почта",
    phoneOptional: "Телефон (необязательно)",
    companyOptional: "Компания (необязательно)",
    howCanWeHelp: "Чем мы можем помочь?",
    tellUsRequirements: "Расскажите о ваших требованиях...",
    sendingMessage: "Отправка...",
    messageSent: "Сообщение отправлено",
    thankYouMessage: "Спасибо за обращение. Мы ответим в течение 24 часов.",
    error: "Ошибка",
    contactInformation: "Контактная информация",
    headquarters: "Главный офис",
    officeAddress: "ул. Церетели 12, Кутаиси, Грузия",
    emailUs: "Напишите нам",
    callUs: "Позвоните нам",
    officeHours: "Рабочие часы",
    company: "Компания",
    servicesFooter: "Услуги",
    contactFooter: "Контакт",
    allRightsReserved: "Все права защищены",
    privacyPolicy: "Политика конфиденциальности",
    termsOfService: "Условия использования",
    serviceNotFound: "Услуга не найдена",
    backToServices: "Назад к услугам",
    brandDescription: "Формируем будущее глобального бизнеса - объединяем независимых профессионалов по всему миру.",
    auditAssurance: "Аудит и гарантии",
    auditDescription: "Аудит — это гораздо больше, чем формальность. Это реальная необходимость для защиты и стимулирования бизнеса.",
    financialServices: "Финансовые услуги",
    financialDescription: "ACG обеспечивает полный спектр услуг для клиентов любого масштаба — от стартапов до крупных частных и публичных компаний. Наша команда финансовых услуг поможет вам эффективно управлять финансами и планировать устойчивый рост.",
    consultingServices: "Консалтинговые услуги",
    consultingDescription: "Наши профессионалы с разнообразным мультидисциплинарным опытом предлагают эффективные решения. Мы предоставляем стратегическое руководство по вопросам бизнес-структуры, стратегий роста и операционной эффективности.",
    businessStructure: "Бизнес-структура",
    businessStructureDesc: "Оптимизация и реорганизация организационной структуры компании для максимальной эффективности.",
    growthStrategies: "Стратегии роста",
    growthStrategiesDesc: "Разработка стратегических планов расширения и развития бизнеса.",
    operationalEfficiency: "Операционная эффективность",
    operationalEfficiencyDesc: "Оптимизация бизнес-процессов для снижения затрат и повышения производительности.",
    multidisciplinaryTeam: "Мультидисциплинарная команда",
    multidisciplinaryTeamDesc: "Объединенный опыт специалистов из различных областей на благо вашего бизнеса.",
    taxConsultancy: "Налоговый консалтинг",
    financialAdvisory: "Финансовый консалтинг",
    riskManagement: "Управление рисками",
    corporateFinance: "Корпоративные финансы",
    recently: "Недавно",
    mondayFriday: "Понедельник - Пятница: 9:00 - 18:00",
    saturdaySunday: "Суббота - Воскресенье: Закрыто",
    integrityQuote: "Честность — основа нашей практики.",
    modernBuilding: "Современное корпоративное здание",
    ourTeamAlt: "Наша команда",
    mapPlaceholder: "Интеграция карты",
    openInMaps: "Открыть в Google Maps",
    viewPortfolio: "Посмотреть портфолио",
    generalEmail: "Общий",
    supportEmail: "Поддержка",
    mainPhone: "Основной",
    faxPhone: "Факс",
    clientSuccess: "Успех клиента",
    aboutTitle: "О компании ACG",
    aboutSubtitle: "Мы являемся ведущей аудиторской и консалтинговой компанией, предоставляющей индивидуальные решения для каждого клиента.",
    aboutWhoWeAre: "Кто мы",
    aboutWhoWeAreDesc: "Мы — мотивированные профессионалы, использующие знания и опыт для решения проблем наших клиентов. Наш подход не стандартный. Наши клиенты полагаются на лучших аудиторов для эффективной работы. Основная философия ACG — высококачественное обслуживание и полная защита клиентов с комплексной поддержкой.",
    aboutIntegraDesc: "Как член Integra International, ведущего международного финансового партнерства, мы предлагаем нашим клиентам доступ к 4000+ профессионалам в 75+ странах. Эта международная поддержка гарантирует квалифицированные услуги в любом формате.",
    aboutMission: "Наша миссия",
    aboutMissionDesc: "Наша поддержка клиентов через стратегическое управление и мониторинг обеспечивает эффективное и полное предоставление услуг, чтобы каждый клиент чувствовал заботу и контроль.",
    aboutJoinSuccess: "Наш опыт поможет вам достичь успеха!",
    aboutExcellence: "Совершенство",
    aboutExcellenceDesc: "Обслуживание высочайшего стандарта.",
    aboutPartnership: "Партнерство",
    aboutPartnershipDesc: "Клиентоориентированный подход.",
    aboutStatClients: "Корпоративных клиентов",
    aboutStatProjects: "Успешных клиентов",
    aboutStatOffices: "Офисов по всему миру",
    aboutStatConsultations: "Успешных проектов",
    aboutMeetingAlt: "Деловая встреча",
    backToTeam: "Назад к команде",
    notFound: "Страница не найдена",
    loanPurposeVerification: "Подтверждение целевого назначения кредита",
    accountingLegislation: "Изучение бухгалтерского учета и законодательства",
    legalServices: "Юридические услуги",
    propertyValuation: "Оценка имущества",
    consulting: "Консалтинг",
    taxDisputesConsulting: "Налоговые споры и консультации",
    blockchainWeb3: "Блокчейн и Web3 решения",
    blockchainSubtitle: "Современная разработка блокчейна, аудит смарт-контрактов и решения децентрализованных приложений для современных предприятий.",
    blockchainIntro: "В быстро развивающемся цифровом ландшафте технология блокчейн представляет собой парадигмальный сдвиг в том, как бизнес работает, проводит транзакции и строит доверие. Подразделение блокчейн и Web3 решений ACG предоставляет экспертизу корпоративного уровня, чтобы помочь вашей организации использовать трансформационную силу децентрализованных технологий.",
    smartContractTitle: "Разработка и аудит смарт-контрактов",
    smartContractDesc: "Наша команда разрабатывает безопасные, эффективные смарт-контракты на EVM-платформах, включая Ethereum и Polygon. Каждый контракт проходит строгий аудит безопасности для выявления уязвимостей перед развертыванием, защищая ваши активы и репутацию.",
    tokenizationTitle: "Токенизация и цифровые активы",
    tokenizationDesc: "От утилитарных токенов до токенов безопасности и NFT — мы проведем вас через весь процесс токенизации. Наши услуги включают дизайн токеномики, реализацию смарт-контрактов, консультации по регуляторному соответствию и интеграцию с существующими бизнес-системами.",
    defiTitle: "DeFi решения",
    defiDesc: "Мы проектируем и разрабатываем протоколы децентрализованных финансов, включая платформы кредитования, децентрализованные биржи, механизмы доходного фермерства и пулы ликвидности. Наши решения отдают приоритет безопасности, масштабируемости и пользовательскому опыту.",
    enterpriseBlockchainTitle: "Корпоративная интеграция блокчейна",
    enterpriseBlockchainDesc: "Свяжите традиционные бизнес-операции с технологией блокчейн. Мы внедряем частные и консорциумные блокчейн-сети для отслеживания цепочки поставок, верификации документов, трансграничных платежей и прозрачных аудиторских процессов.",
    web3AppTitle: "Разработка Web3 приложений",
    web3AppDesc: "Стройте будущее с децентрализованными приложениями (dApps), которые используют блокчейн для бездоверительных операций. От концепции до развертывания, наши услуги разработки Web3 полного стека охватывают фронтенд-интерфейсы, бэкенды смарт-контрактов и интеграцию кошельков.",
  },
  tr: {
    home: "Ana Sayfa",
    aboutUs: "Hakkımızda",
    services: "Hizmetler",
    team: "Ekip",
    partners: "Ortaklar",
    insights: "Haberler",
    contact: "İletişim",
    contacts: "İletişim",
    getConsultation: "Danışmanlık Alın",
    heroTitle: "ACG",
    heroTitleHighlight: "Kutaisi Şubesi",
    heroDescription: "Kalitenin hizmetle buluştuğu ve başarıya ulaşmanın zorunlu olduğu bir yer. Müşterilerimizin sorunlarını çözmek için bilgi ve deneyimi kullanan iş profesyonelleriyiz.",
    exploreServices: "Hizmetleri Keşfet",
    yearsExperience: "Yıllık Deneyim",
    corporateClients: "Kurumsal Müşteri",
    successfulAudits: "Başarılı Denetim",
    consultants: "Danışman",
    ourExpertise: "Uzmanlığımız",
    comprehensiveSolutions: "Kapsamlı Finansal Çözümler",
    viewAllServices: "Tüm Hizmetleri Gör",
    learnMore: "Daha fazla bilgi",
    whyChooseUs: "Neden Biz",
    partnerYouCanTrust: "Güvenebileceğiniz Bir Ortak",
    trustDescription: "Şeffaflık, uzmanlık ve ölçülebilir sonuçlara dayalı uzun vadeli ortaklıklar kurmaya inanıyoruz.",
    strategicInsight: "Stratejik İçgörü",
    strategicInsightDesc: "Sürdürülebilir büyüme için veriye dayalı kararlar.",
    globalCompliance: "Küresel Uyum",
    globalComplianceDesc: "Uluslararası düzenlemelerde uzman navigasyon.",
    riskMitigation: "Risk Azaltma",
    riskMitigationDesc: "Finansal tehditlerin proaktif tespiti.",
    readyToElevate: "Finansal stratejinizi yükseltmeye hazır mısınız?",
    scheduleConsultation: "Kıdemli ortaklarımızla bugün bir danışmanlık planlayın ve işletme performansınızı nasıl optimize edebileceğimizi keşfedin.",
    getStartedToday: "Bugün Başlayın",
    ourPeople: "Ekibimiz",
    meetThePartners: "Ortaklarla Tanışın",
    teamDescription: "Ekibimiz, mükemmellik ve müşteri başarısı tutkusuyla birleşen üst düzey firmalardan onlarca yıllık deneyimi bir araya getiriyor.",
    insightsAndNews: "Haberler ve Güncellemeler",
    insightsDescription: "Düzenleyici değişiklikler, pazar trendleri ve finansal stratejiler hakkında uzman görüşleri.",
    readArticle: "Makaleyi Oku",
    ourServices: "Hizmetlerimiz",
    servicesDescription: "Benzersiz iş zorluklarınıza özel kapsamlı denetim, vergi ve danışmanlık çözümleri.",
    viewDetails: "Detayları Gör",
    contactUs: "Bize Ulaşın",
    contactDescription: "Bir sohbet başlatmaya hazır mısınız? Finansal geleceğinizde size yol göstermeye hazırız.",
    sendMessage: "Mesaj Gönder",
    formDescription: "Aşağıdaki formu doldurun, ekibimiz en kısa sürede size dönecektir.",
    fullName: "Ad Soyad",
    emailAddress: "E-posta Adresi",
    phoneOptional: "Telefon (İsteğe bağlı)",
    companyOptional: "Şirket (İsteğe bağlı)",
    howCanWeHelp: "Size nasıl yardımcı olabiliriz?",
    tellUsRequirements: "Gereksinimlerinizi bize anlatın...",
    sendingMessage: "Gönderiliyor...",
    messageSent: "Mesaj Gönderildi",
    thankYouMessage: "Bizimle iletişime geçtiğiniz için teşekkür ederiz. 24 saat içinde yanıt vereceğiz.",
    error: "Hata",
    contactInformation: "İletişim Bilgileri",
    headquarters: "Merkez Ofis",
    officeAddress: "Tsereteli 12, Kutaisi, Gürcistan",
    emailUs: "E-posta Gönderin",
    callUs: "Bizi Arayın",
    officeHours: "Çalışma Saatleri",
    company: "Şirket",
    servicesFooter: "Hizmetler",
    contactFooter: "İletişim",
    allRightsReserved: "Tüm hakları saklıdır",
    privacyPolicy: "Gizlilik Politikası",
    termsOfService: "Hizmet Şartları",
    serviceNotFound: "Hizmet Bulunamadı",
    backToServices: "Hizmetlere Dön",
    brandDescription: "Küresel iş dünyasının geleceğini şekillendirmek - bağımsız profesyonelleri dünya çapında bir araya getirmek.",
    auditAssurance: "Denetim ve Güvence",
    auditDescription: "Denetim bir formaliteden çok daha fazlasıdır. İşletmeyi korumak ve teşvik etmek için gerçek bir gerekliliktir.",
    financialServices: "Finansal Hizmetler",
    financialDescription: "ACG, start-up'lardan büyük özel ve halka açık şirketlere kadar her ölçekteki müşteriye kapsamlı hizmet sunmaktadır. Finansal hizmetler ekibimiz, finanslarınızı etkin bir şekilde yönetmenize ve sürdürülebilir büyüme planlamanıza yardımcı olacaktır.",
    consultingServices: "Danışmanlık Hizmetleri",
    consultingDescription: "Çeşitli multidisipliner deneyime sahip profesyonellerimiz etkili çözümler sunmaktadır. İş yapısı, büyüme stratejileri ve operasyonel verimlilik konularında stratejik rehberlik sağlıyoruz.",
    businessStructure: "İş Yapısı",
    businessStructureDesc: "Maksimum verimlilik için şirket organizasyon yapısının optimizasyonu ve yeniden düzenlenmesi.",
    growthStrategies: "Büyüme Stratejileri",
    growthStrategiesDesc: "İş genişlemesi ve gelişimi için stratejik planların geliştirilmesi.",
    operationalEfficiency: "Operasyonel Verimlilik",
    operationalEfficiencyDesc: "Maliyetleri düşürmek ve verimliliği artırmak için iş süreçlerinin optimizasyonu.",
    multidisciplinaryTeam: "Multidisipliner Ekip",
    multidisciplinaryTeamDesc: "İşletmenizin yararına çeşitli alanlardan uzmanların birleşik deneyimi.",
    taxConsultancy: "Vergi Danışmanlığı",
    financialAdvisory: "Finansal Danışmanlık",
    riskManagement: "Risk Yönetimi",
    corporateFinance: "Kurumsal Finans",
    recently: "Son Zamanlarda",
    mondayFriday: "Pazartesi - Cuma: 9:00 - 18:00",
    saturdaySunday: "Cumartesi - Pazar: Kapalı",
    integrityQuote: "Dürüstlük, uygulamamızın temelidir.",
    modernBuilding: "Modern Kurumsal Bina",
    ourTeamAlt: "Ekibimiz",
    mapPlaceholder: "Harita Entegrasyonu",
    openInMaps: "Google Maps'te Aç",
    viewPortfolio: "Portföyü Görüntüle",
    generalEmail: "Genel",
    supportEmail: "Destek",
    mainPhone: "Ana",
    faxPhone: "Faks",
    clientSuccess: "Müşteri Başarısı",
    aboutTitle: "ACG Hakkında",
    aboutSubtitle: "Her müşteri için bireysel çözümler sunan lider denetim ve danışmanlık şirketiyiz.",
    aboutWhoWeAre: "Biz Kimiz",
    aboutWhoWeAreDesc: "Müşterilerimizin sorunlarını çözmek için bilgi ve deneyimi kullanan motive profesyonelleriz. Yaklaşımımız standart değildir. Müşterilerimiz en iyi denetçilere güvenir. ACG'nin temel felsefesi yüksek kaliteli hizmet sunumu ve kapsamlı destekle tam müşteri korumasıdır.",
    aboutIntegraDesc: "Integra International üyesi olarak, önde gelen uluslararası finans ortaklığı kapsamında müşterilerimize 75+ ülkede 4000+ profesyonele erişim sunuyoruz. Bu uluslararası destek, her formatta nitelikli hizmetler garanti eder.",
    aboutMission: "Misyonumuz",
    aboutMissionDesc: "Stratejik yönetim ve izleme yoluyla müşterilerimize desteğimiz, hizmetlerin etkili ve eksiksiz sunulmasını sağlar, böylece her müşteri ilgi ve kontrol hisseder.",
    aboutJoinSuccess: "Deneyimimiz başarıya ulaşmanıza yardımcı olacak!",
    aboutExcellence: "Mükemmellik",
    aboutExcellenceDesc: "En yüksek standartlarda hizmet sunumu.",
    aboutPartnership: "Ortaklık",
    aboutPartnershipDesc: "Müşteri odaklı yaklaşım.",
    aboutStatClients: "Kurumsal Müşteri",
    aboutStatProjects: "Başarılı Müşteri",
    aboutStatOffices: "Dünya Genelinde Ofis",
    aboutStatConsultations: "Başarılı Proje",
    aboutMeetingAlt: "İş Toplantısı",
    backToTeam: "Takıma Dön",
    notFound: "Sayfa Bulunamadı",
    loanPurposeVerification: "Kredi Amacı Doğrulama",
    accountingLegislation: "Muhasebe ve Mevzuat İncelemesi",
    legalServices: "Hukuk Hizmetleri",
    propertyValuation: "Mülk Değerleme",
    consulting: "Danışmanlık",
    taxDisputesConsulting: "Vergi Uyuşmazlıkları ve Danışmanlık",
    blockchainWeb3: "Blockchain ve Web3 Çözümleri",
    blockchainSubtitle: "Modern işletmeler için modern blockchain geliştirme, akıllı sözleşme denetimi ve merkeziyetsiz uygulama çözümleri.",
    blockchainIntro: "Hızla gelişen dijital ortamda, blockchain teknolojisi işletmelerin nasıl çalıştığı, işlem yaptığı ve güven inşa ettiği konusunda paradigma değişimini temsil etmektedir. ACG'nin Blockchain ve Web3 Çözümleri bölümü, kuruluşunuzun merkeziyetsiz teknolojilerin dönüştürücü gücünden yararlanmasına yardımcı olmak için kurumsal düzeyde blockchain uzmanlığı sunmaktadır.",
    smartContractTitle: "Akıllı Sözleşme Geliştirme ve Denetim",
    smartContractDesc: "Ekibimiz Ethereum ve Polygon dahil EVM tabanlı blockchain platformlarında güvenli, verimli akıllı sözleşmeler geliştirir. Her sözleşme, dağıtımdan önce güvenlik açıklarını tespit etmek için titiz güvenlik denetimlerinden geçerek varlıklarınızı ve itibarınızı korur.",
    tokenizationTitle: "Tokenizasyon ve Dijital Varlıklar",
    tokenizationDesc: "Fayda tokenlerinden güvenlik tokenlerine ve NFT'lere kadar, tüm tokenizasyon sürecinde size rehberlik ediyoruz. Hizmetlerimiz tokenomics tasarımı, akıllı sözleşme uygulaması, düzenleyici uyumluluk danışmanlığı ve mevcut iş sistemleriyle entegrasyonu kapsamaktadır.",
    defiTitle: "DeFi Çözümleri",
    defiDesc: "Borç verme platformları, merkeziyetsiz borsalar, verim çiftçiliği mekanizmaları ve likidite havuzları dahil olmak üzere merkeziyetsiz finans protokolleri tasarlıyor ve geliştiriyoruz. Çözümlerimiz güvenlik, ölçeklenebilirlik ve kullanıcı deneyimine öncelik verir.",
    enterpriseBlockchainTitle: "Kurumsal Blockchain Entegrasyonu",
    enterpriseBlockchainDesc: "Geleneksel iş operasyonlarını blockchain teknolojisiyle bağlayın. Tedarik zinciri takibi, belge doğrulaması, sınır ötesi ödemeler ve şeffaf denetim süreçleri için özel ve konsorsiyum blockchain ağları uyguluyoruz.",
    web3AppTitle: "Web3 Uygulama Geliştirme",
    web3AppDesc: "Güvensiz operasyonlar için blockchain kullanan merkeziyetsiz uygulamalarla (dApps) geleceği inşa edin. Konseptten dağıtıma kadar, tam yığın Web3 geliştirme hizmetlerimiz ön yüz arayüzlerini, akıllı sözleşme arka uçlarını ve cüzdan entegrasyonlarını kapsar.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("language");
      if (saved && (saved === "ka" || saved === "en" || saved === "ru" || saved === "tr")) {
        return saved;
      }
    }
    return "ka";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: keyof typeof translations.en): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  const getText = (obj: I18nString | string | unknown): string => {
    if (typeof obj === "string") return obj;
    if (obj && typeof obj === "object" && language in obj) {
      return (obj as I18nString)[language] || "";
    }
    return "";
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getText }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
