import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "ka" | "en" | "ru" | "tr";

export interface I18nString {
  ka: string;
  en: string;
  ru: string;
  tr: string;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.en) => string;
  getText: (obj: I18nString | string | unknown) => string;
}

const translations = {
  ka: {
    home: "მთავარი",
    services: "სერვისები",
    team: "გუნდი",
    insights: "სიახლეები",
    contact: "კონტაქტი",
    getConsultation: "მიიღეთ კონსულტაცია",
    heroTitle: "ექსპერტული აუდიტი და",
    heroTitleHighlight: "სტრატეგიული კონსულტაცია",
    heroDescription: "ჩვენ გთავაზობთ სიზუსტეს, სიცხადეს და შორსმჭვრეტელობას, რათა თქვენს ბიზნესს დავეხმაროთ რთული ფინანსური გარემოს ნავიგაციასა და მდგრადი ზრდის მიღწევაში.",
    exploreServices: "სერვისების ნახვა",
    yearsExperience: "წლიანი გამოცდილება",
    corporateClients: "კორპორატიული კლიენტი",
    successfulAudits: "წარმატებული აუდიტი",
    consultants: "კონსულტანტი",
    ourExpertise: "ჩვენი ექსპერტიზა",
    comprehensiveSolutions: "კომპლექსური ფინანსური გადაწყვეტილებები",
    viewAllServices: "ყველა სერვისის ნახვა",
    learnMore: "გაიგეთ მეტი",
    whyChooseUs: "რატომ ჩვენ",
    partnerYouCanTrust: "პარტნიორი, რომელსაც შეგიძლიათ ენდოთ",
    trustDescription: "ჩვენ გვჯერა გრძელვადიანი პარტნიორობის შექმნის გამჭვირვალობის, ექსპერტიზისა და გაზომვადი შედეგების საფუძველზე.",
    strategicInsight: "სტრატეგიული ხედვა",
    strategicInsightDesc: "მონაცემებზე დაფუძნებული გადაწყვეტილებები მდგრადი ზრდისთვის.",
    globalCompliance: "გლობალური შესაბამისობა",
    globalComplianceDesc: "საერთაშორისო რეგულაციების ექსპერტული ნავიგაცია.",
    riskMitigation: "რისკების შერბილება",
    riskMitigationDesc: "ფინანსური საფრთხეების პროაქტიული იდენტიფიკაცია.",
    readyToElevate: "მზად ხართ თქვენი ფინანსური სტრატეგიის გასაუმჯობესებლად?",
    scheduleConsultation: "დანიშნეთ კონსულტაცია ჩვენს უფროს პარტნიორებთან და აღმოაჩინეთ, როგორ შეგვიძლია დაგეხმაროთ.",
    getStartedToday: "დაიწყეთ დღეს",
    ourPeople: "ჩვენი ხალხი",
    meetThePartners: "გაიცანით პარტნიორები",
    teamDescription: "ჩვენი გუნდი აერთიანებს ათწლეულების გამოცდილებას წამყვანი ფირმებიდან.",
    insightsAndNews: "სიახლეები და ახალი ამბები",
    insightsDescription: "ექსპერტული პერსპექტივები მარეგულირებელ ცვლილებებზე და ფინანსურ სტრატეგიებზე.",
    readArticle: "წაიკითხეთ სტატია",
    ourServices: "ჩვენი სერვისები",
    servicesDescription: "კომპლექსური აუდიტი, საგადასახადო და საკონსულტაციო გადაწყვეტილებები.",
    viewDetails: "დეტალების ნახვა",
    contactUs: "დაგვიკავშირდით",
    contactDescription: "მზად ხართ საუბრის დასაწყებად? ჩვენ აქ ვართ დასახმარებლად.",
    sendMessage: "გაგზავნეთ შეტყობინება",
    formDescription: "შეავსეთ ფორმა და ჩვენი გუნდი მალე დაგიკავშირდებათ.",
    fullName: "სრული სახელი",
    emailAddress: "ელ. ფოსტა",
    phoneOptional: "ტელეფონი (არასავალდებულო)",
    companyOptional: "კომპანია (არასავალდებულო)",
    howCanWeHelp: "როგორ შეგვიძლია დაგეხმაროთ?",
    tellUsRequirements: "გვითხარით თქვენი მოთხოვნილებების შესახებ...",
    sendingMessage: "იგზავნება...",
    messageSent: "შეტყობინება გაიგზავნა",
    thankYouMessage: "გმადლობთ დაკავშირებისთვის. 24 საათში გიპასუხებთ.",
    error: "შეცდომა",
    contactInformation: "საკონტაქტო ინფორმაცია",
    headquarters: "მთავარი ოფისი",
    emailUs: "მოგვწერეთ",
    callUs: "დაგვირეკეთ",
    officeHours: "სამუშაო საათები",
    company: "კომპანია",
    servicesFooter: "სერვისები",
    contactFooter: "კონტაქტი",
    allRightsReserved: "ყველა უფლება დაცულია",
    privacyPolicy: "კონფიდენციალურობის პოლიტიკა",
    termsOfService: "მომსახურების პირობები",
    serviceNotFound: "სერვისი ვერ მოიძებნა",
    backToServices: "სერვისებზე დაბრუნება",
    brandDescription: "გლობალური ბიზნესის მომავლის ფორმირება - ვაერთიანებთ დამოუკიდებელ პროფესიონალებს მსოფლიო მასშტაბით.",
    auditAssurance: "აუდიტი და უზრუნველყოფა",
    taxConsultancy: "საგადასახადო კონსულტაცია",
    financialAdvisory: "ფინანსური კონსულტაცია",
    riskManagement: "რისკების მართვა",
    corporateFinance: "კორპორატიული ფინანსები",
    recently: "ახლახანს",
    mondayFriday: "ორშაბათი - პარასკევი: 9:00 - 18:00",
    saturdaySunday: "შაბათი - კვირა: დაკეტილია",
    integrityQuote: "მთლიანობა ჩვენი პრაქტიკის საფუძველია.",
    modernBuilding: "თანამედროვე კორპორატიული შენობა",
    ourTeamAlt: "ჩვენი გუნდი",
    mapPlaceholder: "რუკის ინტეგრაცია",
    generalEmail: "ზოგადი",
    supportEmail: "მხარდაჭერა",
    mainPhone: "მთავარი",
    faxPhone: "ფაქსი",
    clientSuccess: "კლიენტის წარმატება",
  },
  en: {
    home: "Home",
    services: "Services",
    team: "Team",
    insights: "Insights",
    contact: "Contact",
    getConsultation: "Get a Consultation",
    heroTitle: "Expert Audit &",
    heroTitleHighlight: "Strategic Consulting",
    heroDescription: "We provide precision, clarity, and foresight to help your business navigate complex financial landscapes and achieve sustainable growth.",
    exploreServices: "Explore Services",
    yearsExperience: "Years Experience",
    corporateClients: "Corporate Clients",
    successfulAudits: "Successful Audits",
    consultants: "Consultants",
    ourExpertise: "Our Expertise",
    comprehensiveSolutions: "Comprehensive Financial Solutions",
    viewAllServices: "View All Services",
    learnMore: "Learn more",
    whyChooseUs: "Why Choose Us",
    partnerYouCanTrust: "A Partner You Can Trust",
    trustDescription: "We believe in building long-term partnerships based on transparency, expertise, and measurable results.",
    strategicInsight: "Strategic Insight",
    strategicInsightDesc: "Data-driven decisions for sustainable growth.",
    globalCompliance: "Global Compliance",
    globalComplianceDesc: "Expert navigation of international regulations.",
    riskMitigation: "Risk Mitigation",
    riskMitigationDesc: "Proactive identification of financial threats.",
    readyToElevate: "Ready to elevate your financial strategy?",
    scheduleConsultation: "Schedule a consultation with our senior partners today and discover how we can help optimize your business performance.",
    getStartedToday: "Get Started Today",
    ourPeople: "Our People",
    meetThePartners: "Meet the Partners",
    teamDescription: "Our team brings together decades of experience from top-tier firms, united by a passion for excellence and client success.",
    insightsAndNews: "Insights & News",
    insightsDescription: "Expert perspectives on regulatory changes, market trends, and financial strategies.",
    readArticle: "Read Article",
    ourServices: "Our Services",
    servicesDescription: "Comprehensive audit, tax, and advisory solutions tailored to your unique business challenges.",
    viewDetails: "View Details",
    contactUs: "Contact Us",
    contactDescription: "Ready to start a conversation? We're here to help you navigate your financial future.",
    sendMessage: "Send Message",
    formDescription: "Fill out the form below and our team will get back to you shortly.",
    fullName: "Full Name",
    emailAddress: "Email Address",
    phoneOptional: "Phone (Optional)",
    companyOptional: "Company (Optional)",
    howCanWeHelp: "How can we help?",
    tellUsRequirements: "Tell us about your requirements...",
    sendingMessage: "Sending Message...",
    messageSent: "Message Sent",
    thankYouMessage: "Thank you for contacting us. We will respond within 24 hours.",
    error: "Error",
    contactInformation: "Contact Information",
    headquarters: "Headquarters",
    emailUs: "Email Us",
    callUs: "Call Us",
    officeHours: "Office Hours",
    company: "Company",
    servicesFooter: "Services",
    contactFooter: "Contact",
    allRightsReserved: "All rights reserved",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    serviceNotFound: "Service Not Found",
    backToServices: "Back to Services",
    brandDescription: "Shaping the future of global business - bringing together independent professionals on a worldwide scale.",
    auditAssurance: "Audit & Assurance",
    taxConsultancy: "Tax Consultancy",
    financialAdvisory: "Financial Advisory",
    riskManagement: "Risk Management",
    corporateFinance: "Corporate Finance",
    recently: "Recently",
    mondayFriday: "Monday - Friday: 9:00 AM - 6:00 PM EST",
    saturdaySunday: "Saturday - Sunday: Closed",
    integrityQuote: "Integrity is the foundation of our practice.",
    modernBuilding: "Modern Corporate Building",
    ourTeamAlt: "Our Team",
    mapPlaceholder: "Map Integration",
    generalEmail: "General",
    supportEmail: "Support",
    mainPhone: "Main",
    faxPhone: "Fax",
    clientSuccess: "Client Success",
  },
  ru: {
    home: "Главная",
    services: "Услуги",
    team: "Команда",
    insights: "Инсайты",
    contact: "Контакт",
    getConsultation: "Получить консультацию",
    heroTitle: "Экспертный аудит и",
    heroTitleHighlight: "Стратегический консалтинг",
    heroDescription: "Мы обеспечиваем точность, ясность и дальновидность, чтобы помочь вашему бизнесу ориентироваться в сложных финансовых условиях.",
    exploreServices: "Изучить услуги",
    yearsExperience: "Лет опыта",
    corporateClients: "Корпоративных клиентов",
    successfulAudits: "Успешных аудитов",
    consultants: "Консультантов",
    ourExpertise: "Наша экспертиза",
    comprehensiveSolutions: "Комплексные финансовые решения",
    viewAllServices: "Все услуги",
    learnMore: "Узнать больше",
    whyChooseUs: "Почему мы",
    partnerYouCanTrust: "Партнер, которому можно доверять",
    trustDescription: "Мы верим в построение долгосрочных партнерств, основанных на прозрачности, экспертизе и измеримых результатах.",
    strategicInsight: "Стратегическое видение",
    strategicInsightDesc: "Решения на основе данных для устойчивого роста.",
    globalCompliance: "Глобальное соответствие",
    globalComplianceDesc: "Экспертная навигация международных регуляций.",
    riskMitigation: "Снижение рисков",
    riskMitigationDesc: "Проактивное выявление финансовых угроз.",
    readyToElevate: "Готовы улучшить свою финансовую стратегию?",
    scheduleConsultation: "Запланируйте консультацию с нашими старшими партнерами и узнайте, как мы можем помочь.",
    getStartedToday: "Начните сегодня",
    ourPeople: "Наши люди",
    meetThePartners: "Познакомьтесь с партнерами",
    teamDescription: "Наша команда объединяет десятилетия опыта из ведущих фирм.",
    insightsAndNews: "Инсайты и новости",
    insightsDescription: "Экспертные перспективы по регуляторным изменениям и финансовым стратегиям.",
    readArticle: "Читать статью",
    ourServices: "Наши услуги",
    servicesDescription: "Комплексные решения по аудиту, налогам и консультированию.",
    viewDetails: "Подробнее",
    contactUs: "Свяжитесь с нами",
    contactDescription: "Готовы начать разговор? Мы здесь, чтобы помочь вам.",
    sendMessage: "Отправить сообщение",
    formDescription: "Заполните форму, и наша команда свяжется с вами.",
    fullName: "Полное имя",
    emailAddress: "Электронная почта",
    phoneOptional: "Телефон (необязательно)",
    companyOptional: "Компания (необязательно)",
    howCanWeHelp: "Чем мы можем помочь?",
    tellUsRequirements: "Расскажите о ваших требованиях...",
    sendingMessage: "Отправка...",
    messageSent: "Сообщение отправлено",
    thankYouMessage: "Спасибо за обращение. Мы ответим в течение 24 часов.",
    error: "Ошибка",
    contactInformation: "Контактная информация",
    headquarters: "Главный офис",
    emailUs: "Напишите нам",
    callUs: "Позвоните нам",
    officeHours: "Рабочие часы",
    company: "Компания",
    servicesFooter: "Услуги",
    contactFooter: "Контакт",
    allRightsReserved: "Все права защищены",
    privacyPolicy: "Политика конфиденциальности",
    termsOfService: "Условия использования",
    serviceNotFound: "Услуга не найдена",
    backToServices: "Назад к услугам",
    brandDescription: "Формируем будущее глобального бизнеса - объединяем независимых профессионалов по всему миру.",
    auditAssurance: "Аудит и гарантии",
    taxConsultancy: "Налоговый консалтинг",
    financialAdvisory: "Финансовый консалтинг",
    riskManagement: "Управление рисками",
    corporateFinance: "Корпоративные финансы",
    recently: "Недавно",
    mondayFriday: "Понедельник - Пятница: 9:00 - 18:00",
    saturdaySunday: "Суббота - Воскресенье: Закрыто",
    integrityQuote: "Честность — основа нашей практики.",
    modernBuilding: "Современное корпоративное здание",
    ourTeamAlt: "Наша команда",
    mapPlaceholder: "Интеграция карты",
    generalEmail: "Общий",
    supportEmail: "Поддержка",
    mainPhone: "Основной",
    faxPhone: "Факс",
    clientSuccess: "Успех клиента",
  },
  tr: {
    home: "Ana Sayfa",
    services: "Hizmetler",
    team: "Ekip",
    insights: "Haberler",
    contact: "İletişim",
    getConsultation: "Danışmanlık Alın",
    heroTitle: "Uzman Denetim ve",
    heroTitleHighlight: "Stratejik Danışmanlık",
    heroDescription: "İşletmenizin karmaşık finansal ortamlarda yol almasına ve sürdürülebilir büyüme elde etmesine yardımcı olmak için hassasiyet, netlik ve öngörü sağlıyoruz.",
    exploreServices: "Hizmetleri Keşfet",
    yearsExperience: "Yıllık Deneyim",
    corporateClients: "Kurumsal Müşteri",
    successfulAudits: "Başarılı Denetim",
    consultants: "Danışman",
    ourExpertise: "Uzmanlığımız",
    comprehensiveSolutions: "Kapsamlı Finansal Çözümler",
    viewAllServices: "Tüm Hizmetleri Gör",
    learnMore: "Daha fazla bilgi",
    whyChooseUs: "Neden Biz",
    partnerYouCanTrust: "Güvenebileceğiniz Bir Ortak",
    trustDescription: "Şeffaflık, uzmanlık ve ölçülebilir sonuçlara dayalı uzun vadeli ortaklıklar kurmaya inanıyoruz.",
    strategicInsight: "Stratejik İçgörü",
    strategicInsightDesc: "Sürdürülebilir büyüme için veriye dayalı kararlar.",
    globalCompliance: "Küresel Uyum",
    globalComplianceDesc: "Uluslararası düzenlemelerde uzman navigasyon.",
    riskMitigation: "Risk Azaltma",
    riskMitigationDesc: "Finansal tehditlerin proaktif tespiti.",
    readyToElevate: "Finansal stratejinizi yükseltmeye hazır mısınız?",
    scheduleConsultation: "Kıdemli ortaklarımızla bugün bir danışmanlık planlayın ve işletme performansınızı nasıl optimize edebileceğimizi keşfedin.",
    getStartedToday: "Bugün Başlayın",
    ourPeople: "Ekibimiz",
    meetThePartners: "Ortaklarla Tanışın",
    teamDescription: "Ekibimiz, mükemmellik ve müşteri başarısı tutkusuyla birleşen üst düzey firmalardan onlarca yıllık deneyimi bir araya getiriyor.",
    insightsAndNews: "Haberler ve Güncellemeler",
    insightsDescription: "Düzenleyici değişiklikler, pazar trendleri ve finansal stratejiler hakkında uzman görüşleri.",
    readArticle: "Makaleyi Oku",
    ourServices: "Hizmetlerimiz",
    servicesDescription: "Benzersiz iş zorluklarınıza özel kapsamlı denetim, vergi ve danışmanlık çözümleri.",
    viewDetails: "Detayları Gör",
    contactUs: "Bize Ulaşın",
    contactDescription: "Bir sohbet başlatmaya hazır mısınız? Finansal geleceğinizde size yol göstermeye hazırız.",
    sendMessage: "Mesaj Gönder",
    formDescription: "Aşağıdaki formu doldurun, ekibimiz en kısa sürede size dönecektir.",
    fullName: "Ad Soyad",
    emailAddress: "E-posta Adresi",
    phoneOptional: "Telefon (İsteğe bağlı)",
    companyOptional: "Şirket (İsteğe bağlı)",
    howCanWeHelp: "Size nasıl yardımcı olabiliriz?",
    tellUsRequirements: "Gereksinimlerinizi bize anlatın...",
    sendingMessage: "Gönderiliyor...",
    messageSent: "Mesaj Gönderildi",
    thankYouMessage: "Bizimle iletişime geçtiğiniz için teşekkür ederiz. 24 saat içinde yanıt vereceğiz.",
    error: "Hata",
    contactInformation: "İletişim Bilgileri",
    headquarters: "Merkez Ofis",
    emailUs: "E-posta Gönderin",
    callUs: "Bizi Arayın",
    officeHours: "Çalışma Saatleri",
    company: "Şirket",
    servicesFooter: "Hizmetler",
    contactFooter: "İletişim",
    allRightsReserved: "Tüm hakları saklıdır",
    privacyPolicy: "Gizlilik Politikası",
    termsOfService: "Hizmet Şartları",
    serviceNotFound: "Hizmet Bulunamadı",
    backToServices: "Hizmetlere Dön",
    brandDescription: "Küresel iş dünyasının geleceğini şekillendirmek - bağımsız profesyonelleri dünya çapında bir araya getirmek.",
    auditAssurance: "Denetim ve Güvence",
    taxConsultancy: "Vergi Danışmanlığı",
    financialAdvisory: "Finansal Danışmanlık",
    riskManagement: "Risk Yönetimi",
    corporateFinance: "Kurumsal Finans",
    recently: "Son Zamanlarda",
    mondayFriday: "Pazartesi - Cuma: 9:00 - 18:00",
    saturdaySunday: "Cumartesi - Pazar: Kapalı",
    integrityQuote: "Dürüstlük, uygulamamızın temelidir.",
    modernBuilding: "Modern Kurumsal Bina",
    ourTeamAlt: "Ekibimiz",
    mapPlaceholder: "Harita Entegrasyonu",
    generalEmail: "Genel",
    supportEmail: "Destek",
    mainPhone: "Ana",
    faxPhone: "Faks",
    clientSuccess: "Müşteri Başarısı",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("language");
      if (saved && (saved === "ka" || saved === "en" || saved === "ru" || saved === "tr")) {
        return saved;
      }
    }
    return "ka";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: keyof typeof translations.en): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  const getText = (obj: I18nString | string | unknown): string => {
    if (typeof obj === "string") return obj;
    if (obj && typeof obj === "object" && language in obj) {
      return (obj as I18nString)[language] || "";
    }
    return "";
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getText }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
